config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'favorites#index'
  resources :favorites, only: [:index, :new, :create]
  resources :users, only: [:show]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :favorites


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    # deviseのUserモデルにパラメーターを許可
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birth_date, :favorite_count])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    if user_signed_in?
    @favorites = current_user.favorites
    favorite_check
    @update_favorites = Favorite.where(update_check: "yes").order(:priority_order)
    @no_update_favorites = Favorite.where(update_check: "no").order(:priority_order)
    end
  end

  def new
    @favorite = Favorite.new
    @existing_priority_order = Favorite.pluck(:priority_order)
    
  end

  def create
    @favorite = Favorite.new(favorite_params)
    if @favorite.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end
end


private

def favorite_params
  params.require(:favorite).permit(:url, :name, :priority_order, :update_check)
        .merge(user_id: current_user.id, content: "nothing")
end

def favorite_check
  require 'nokogiri'
  require 'open-uri'
  
  # favoriteごとに対して前回のコンテンツと最新のコンテンツをチェック
  @favorites.each do |favorite|
      # 最新のコンテンツ
      latest_content = Nokogiri::HTML(URI.open(favorite.url))
      # 前回のコンテンツ
      previous_content = favorite.content  #登録直後のfavorite.contentの値は「"nothing"」と設定

      if latest_content.to_s != previous_content.to_s
        # 登録直後の場合、または更新を確認した(前回のコンテンツと何らかの違いがあった)場合の処理
        favorite.update(update_check: "yes")
        favorite.update(content: latest_content.to_s)
      else
        favorite.update(update_check: "no")
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  
  def show
    @user = User.find(current_user.id)
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<div class='favorite-list'>
  <% if user_signed_in?  %>

      <% if @favorites.present? %>
      <div class="favorite-list-title">
      <%= "【 お気に入りリスト 】" %><br>
      </div>
      <div class="favorite-content">
        <div class="favorite-list">
        <% @update_favorites.each do |favorite| %>
          <div class="update-favorite-item">
            
              <span class="new"><%= "[ NEW ]" %> </span>
              <%= link_to favorite.name, favorite.url, target: "_blank" %>
              <span class="new"><%= "[ NEW ]" %> </span>
          </div>

        <% end %>
        </div>
      <br>

     
        <div class="favorite-list">
        <% @no_update_favorites.each do |favorite| %>
          <div class="favorite-item">
            
              <%= link_to favorite.name, favorite.url, target: "_blank" %>
         
          </div>
       
        <% end %>
        </div>
      </div>
      <% else %>
        <br>
        <span>お気に入りの登録がありません<br></span>
        </div>
      <% end %>

  <% else %>
        <br>
        <span>
        ここでは登録したお気に入りのサイトが<br>
        更新されているか確認することができます。<br>
        機能の利用にはユーザー登録が必要です。
        </span>
        </div>
  <% end %>



</div>

app/views/favorites/new.html.erb
<div class="favorites-registration-main">
    <h2 class="favorites-registration">お気に入りのWebサイトの情報を入力</h2>
    <%= form_with model: @favorite, data:{turbo: false}, local: true do |f| %>

  <label class="form-text">WebサイトのURL</label>
  <br>
  <%= f.text_area :url, class:"favorites-info", id:"favorite-url", placeholder:"http://〜〜〜〜〜" %>
  <br>
  <br>

  <label class="form-text">Webサイトの名前</label>
  <br>
  <%= f.text_area :name, class:"favorites-info", id:"favorite-name", placeholder:"(50文字まで)", maxlength:"50" %>
  <br>
  <br>

  <label class="form-text">一覧での優先表示順位</label>
  <br>
  <%= f.select :priority_order, (1..20).to_a - @existing_priority_order %>
  <br>
  <br>

  <%= f.submit "登録する" ,class:"button" %>
 <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OSKチェッカー</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="title"><a href="/">OSKチェッカー</a></h1>



        <% if user_signed_in? %>
          <div class="user_menu">
            <div class="user_name">
            <%= "#{current_user.nickname} 様　ログイン中" %>
            <br>

            </div>
              <%= link_to "マイページ", "/users/#{current_user.id}", class: "button" %>
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: "button" %>
          </div>
        <% else %>
          <div class="user_menu">
            <div class="user_name">
            <%= "未ログイン" %>
            </div>
              <%= link_to "ログイン", new_user_session_path, class: "button" %>
              <%= link_to "新規登録", new_user_registration_path, class: "button" %>
          </div>
        <% end %>
      </div>
     <br>

    </header>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="my_page">
  <p><%= @user.nickname %>様のマイページ</p>
 
</div>

<div class="favorite_registration">
  <%= link_to "お気に入りを登録する", new_favorite_path, class: "button" %>
</div>